services:
  postgres:
    image: postgres:14-alpine
    container_name: terrabound_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - terrabound_pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 10

# remove these comments when implementing AI
  # tf:
  #   image: tensorflow/serving
  #   container_name: template_tf
  #   environment:
  #     - MODEL_NAME=ttt
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8501/"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "8501"
  #   volumes:
  #     - ./model:/models/ttt
  #   restart: unless-stopped

  nakama:
    image: heroiclabs/nakama:3.34.1
    container_name: terrabound_nakama
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable
    volumes:
      - ../backend/build/backend.so:/nakama/data/modules/backend.so:ro
      - ./config/local.yml:/nakama/data/local.yml:ro
    environment:
      - NAKAMA_DATA_DIR=/nakama/data
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  terrabound_pgdata:
